"use-strict";

const tokenProperties = {
  access_token: {
    type: "string",
    description: "A JSON Web Token granting authorization"
  },

  expire_at: {
    type: "string",
    format: "date-time",
    description: "The precise date and time when a token will expire and no longer be valid",
  },

  payload_token: {
    type: "string",
    description: "A JSON Web Token generated by the server"
  }
};

export default tokenProperties;
