services:
  nginx:
    build:
      context: services/nginx/
      dockerfile: Dockerfile.ibertran
    image: ibertran/transcendence-nginx
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:7979:7979"
    networks:
      - frontend
      - avatars
      - settings
      - documentation
      - social
    depends_on:
      - avatars

  frontend:
    build:
      context: services/frontend/
      dockerfile: Dockerfile
    image: ibertran/transcendence-frontend
    volumes:
      - ./services/frontend/src:/services/frontend/src
      - ./services/frontend/public:/services/frontend/public
      - ./modules/:/modules:ro
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - WS_URL=${WS_URL}
    networks:
      - frontend

  credentials:
    build:
      context: services/credentials/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/credentials/srcs:/services/credentials/srcs
      - ./modules/:/modules:ro
      - sqlite:/database
    ports:
      - "127.0.0.1:7002:3000"
    networks:
      - credentials
      - db-profiles

  token-manager:
    build:
      context: services/token-manager/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/token-manager/srcs:/services/token-manager/srcs
      - ./modules/:/modules:ro
      - sqlite:/database
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    networks:
      - frontend
      - tokens

  registration:
    build:
      context: services/registration/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/registration/srcs:/services/registration/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    networks:
      - credentials
      - frontend
    
  password-auth:
    build:
      context: services/password-auth/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/password-auth/srcs:/services/password-auth/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    networks:
      - credentials
      - frontend
      - tokens
  
  fortytwo-auth:
    build:
      context: services/fortytwo-auth/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/fortytwo-auth/srcs:/services/fortytwo-auth/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - JWT_SECRET=${JWT_SECRET}
      - API42_CLIENT_ID=${API42_CLIENT_ID}
      - API42_SECRET=${API42_SECRET}
      - API42_REDIRECT_URI=${API42_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    networks:
      - credentials
      - frontend
      - tokens
      - db-profiles
      - avatars

  lobbies:
    depends_on:
      - matchmaking
    build:
      context: services/lobbies/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/lobbies/srcs:/services/lobbies/srcs
      - ./modules/:/modules:ro
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MATCHMAKING_JWT_SECRET=${MATCHMAKING_JWT_SECRET}
    networks:
      - frontend
      - db-profiles

  matchmaking:
    build:
      context: services/matchmaking/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/matchmaking/srcs:/services/matchmaking/srcs
      - ./modules/:/modules:ro
      - sqlite:/database
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MATCHMAKING_JWT_SECRET=${MATCHMAKING_JWT_SECRET}
      - MATCHMAKING_SCHEDULER_DELAY=${MATCHMAKING_SCHEDULER_DELAY}
    networks:
      - frontend

  db-profiles:
    build:
      context: services/db-profiles/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/db-profiles/srcs:/services/db-profiles/srcs
      - ./modules/:/modules:ro
      - sqlite:/database
    environment:
      - CDN_JWT_SECRET=${CDN_JWT_SECRET}
      - CDN_URL=${CDN_URL}
    networks:
      - db-profiles

  users:
    build:
      context: services/users/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/users/srcs:/services/users/srcs
      - ./modules/:/modules:ro
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
     - frontend
     - db-profiles

  settings:
    build:
      context: services/settings/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/settings/srcs:/services/settings/srcs
      - ./modules/:/modules:ro
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    networks:
      - settings
      - avatars
      - db-profiles
      - credentials
      - tokens

  avatars:
    build:
      context: services/avatars/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/avatars/srcs:/services/avatars/srcs
      - ./modules/:/modules:ro
      - sqlite:/database
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CDN_JWT_SECRET=${CDN_JWT_SECRET}
      - CDN_URL=${CDN_URL}
    networks:
      - avatars
      - cdn-test
    depends_on:
      cdn-nginx:
        condition: service_healthy

  social:
    build:
      context: services/social/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/social/srcs:/services/social/srcs
      - ./modules/:/modules:ro
      - sqlite:/database
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SOCIAL_OFFLINE_DELAY=${SOCIAL_OFFLINE_DELAY}
      - SOCIAL_INACTIVITY_DELAY=${SOCIAL_INACTIVITY_DELAY}
    networks:
      - social
      - db-profiles
      - settings


  cdn-nginx:
    build:
      context: services/CDN/nginx/
      dockerfile: Dockerfile.ibertran
    ports:
      - "127.0.0.1:8181:8181"
    volumes:
      - avatars:/app/avatars/users/:ro
      - ./services/CDN/.avatars:/app/avatars/default/:ro
    networks:
      - cdn-api
      - cdn-test
    depends_on:
      cdn-api:
        condition: service_healthy

  cdn-api:
    build:
      context: services/CDN/api/
      dockerfile: Dockerfile.dev
    volumes:
      - avatars:/app/avatars/users/
      - ./services/CDN/.avatars:/app/avatars/default/:ro
      - ./services/CDN/api/srcs:/services/CDN/api/srcs
      - ./modules/:/modules:ro
    environment:
      - CDN_JWT_SECRET=${CDN_JWT_SECRET}
    networks:
     - cdn-api

networks:
  frontend:
    driver: bridge
  credentials:
    driver: bridge
  db-profiles:
    driver: bridge
  tokens:
    driver: bridge
  settings:
    driver: bridge
  documentation:
    driver: bridge
  avatars:
    driver: bridge
  social:
    driver: bridge
  cdn-api:
    driver: bridge
  swagger:
    driver: bridge

  cdn-test:
    driver: bridge
    
volumes:
  avatars:
  sqlite:
