services:
  nginx:
    build: services/nginx/
    ports:
      - "8080:8080"
      - "7979:7979"
    networks:
      - frontend
      - db-profiles
      - settings
      - swagger
    environment:
      - NGINX_HOST=localhost
    secrets:
      - ssl-crt
      - ssl-key

  frontend:
    build:
      context: services/frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/frontend/src:/services/frontend/src
      - ./services/frontend/public:/services/frontend/public
      - ./modules/:/modules:ro
    environment:
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - "127.0.0.1:4242:8080"
    networks:
      - frontend

  credentials:
    build:
      context: services/credentials/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/credentials/srcs:/services/credentials/srcs
      - ./modules/:/modules:ro
      - ./sqlite:/database
    ports:
      - "127.0.0.1:7002:3000"
    networks:
      - credentials
      - db-profiles

  token-manager:
    build:
      context: services/token-manager/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/token-manager/srcs:/services/token-manager/srcs
      - ./modules/:/modules:ro
      - ./sqlite:/database
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    ports:
      - 127.0.0.1:4002:3000
    networks:
      - frontend
      - tokens

  registration:
    build:
      context: services/registration/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/registration/srcs:/services/registration/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    ports:
      - "127.0.0.1:4012:3000"
    networks:
      - credentials
      - frontend
    
  password-auth:
    build:
      context: services/password-auth/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/password-auth/srcs:/services/password-auth/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    ports:
      - "127.0.0.1:4022:3000"
    networks:
      - credentials
      - frontend
      - tokens
  
  fortytwo-auth:
    build:
      context: services/fortytwo-auth/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/fortytwo-auth/srcs:/services/fortytwo-auth/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - JWT_SECRET=${JWT_SECRET}
      - API42_CLIENT_ID=${API42_CLIENT_ID}
      - API42_SECRET=${API42_SECRET}
      - API42_REDIRECT_URI=${API42_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    ports:
      - "127.0.0.1:4042:3000"
    networks:
      - credentials
      - frontend
      - tokens
      - db-profiles

  lobbies:
    build:
      context: services/lobbies/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/lobbies/srcs:/services/lobbies/srcs
      - ./modules/:/modules:ro
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "127.0.0.1:4043:3000"
    # networks:

  # profiles-api:
  #   build:
  #     context: services/profiles-api/
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./sqlite:/database
  #     - ./services/profiles-api/srcs:/run/srcs
  #   ports:
  #     - "127.0.0.1:3003:3000"
  #   networks:
  #     - credentials

  db-profiles:
    build:
      context: services/db-profiles/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/db-profiles/srcs:/services/db-profiles/srcs
      - ./modules/:/modules:ro
      - ./sqlite:/database
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 127.0.0.1:7001:3000
    networks:
      - db-profiles

  users:
    build:
      context: services/users/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/users/srcs:/services/users/srcs
      - ./modules/:/modules:ro
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 127.0.0.1:4003:3000
    networks:
     - frontend
     - db-profiles

  # settings:
  #   build:
  #     context: services/settings/
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./services/settings/srcs:/services/settings/srcs
  #     - ./modules/:/modules:ro
  #   environment:
  #     - JWT_SECRET=${JWT_SECRET}
  #   ports:
  #     - 127.0.0.1:4004:3000
  #   networks:
  #     - settings

  swagger:
    build:
      context: services/swagger/
      dockerfile: Dockerfile.dev
    volumes:
      - ./documentation/:/documentation/:ro
      - ./services/swagger/srcs:/services/swagger/srcs
      - ./modules/:/modules:ro
    environment:
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - 42000:3000
    networks:
      - swagger


networks:
  frontend:
    driver: bridge
  credentials:
    driver: bridge
  db-profiles:
    driver: bridge
  tokens:
    driver: bridge
  settings:
    driver: bridge
  swagger:
    driver: bridge

secrets:
  ssl-crt: 
    file: ./secrets/localhost.crt
  ssl-key: 
    file: ./secrets/localhost.key
