services:
  nginx:
    build: services/nginx/
    ports:
      - "8080:8080"
      - "7979:7979"
    networks:
      - frontend
    environment:
      - NGINX_HOST=localhost
    secrets:
      - ssl-crt
      - ssl-key

  credentials:
    build:
      context: services/credentials/
      dockerfile: Dockerfile.dev
    volumes:
      - ./sqlite:/database
      - ./services/credentials/srcs:/services/credentials/srcs
      - ./modules/:/modules:ro
    ports:
      - "127.0.0.1:7002:3000"
    networks:
      - credentials

  token-manager:
    build:
      context: services/token-manager/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/token-manager/srcs:/services/token-manager/srcs
      - ./modules/:/modules:ro
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    ports:
      - 127.0.0.1:4002:3000
    networks:
      - frontend
      - tokens

  registration:
    build:
      context: services/registration/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/registration/srcs:/services/registration/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
    ports:
      - "127.0.0.1:4012:3000"
    networks:
      - credentials
      - frontend
    
  password-auth:
    build:
      context: services/password-auth/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/password-auth/srcs:/services/password-auth/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - TOKEN_MANAGER_SECRET=${TOKEN_MANAGER_SECRET}
    ports:
      - "127.0.0.1:4022:3000"
    networks:
      - credentials
      - frontend
      - tokens
  
  fortytwo-auth:
    build:
      context: services/fortytwo-auth/
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/fortytwo-auth/srcs:/services/fortytwo-auth/srcs
      - ./modules/:/modules:ro
    environment:
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - JWT_SECRET=${JWT_SECRET}
      - API42_CLIENT_ID=${API42_CLIENT_ID}
      - API42_SECRET=${API42_SECRET}
      - API42_REDIRECT_URI=${API42_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "127.0.0.1:4042:3000"
    networks:
      - credentials
      - frontend
      - tokens

  # profiles-api:
  #   build:
  #     context: services/profiles-api/
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./sqlite:/database
  #     - ./services/profiles-api/srcs:/run/srcs
  #   ports:
  #     - "127.0.0.1:3003:3000"
  #   networks:
  #     - credentials


networks:
  frontend:
    driver: bridge
  credentials:
    driver: bridge
  profiles:
    driver: bridge
  tokens:
    driver: bridge

secrets:
  ssl-crt: 
    file: ./secrets/localhost.crt
  ssl-key: 
    file: ./secrets/localhost.key
