FROM node:23.7-alpine3.20

WORKDIR /services/lobbies/
COPY package*.json .

RUN npm install -g nodemon
RUN npm install

ENTRYPOINT [ "nodemon", "--watch", "/modules/yatt-utils", "--watch", "/modules/yatt-lobbies", "--watch", "./srcs" , "srcs/index.js" ]

EXPOSE 3000
