FROM node:23.7-alpine3.20

ARG ASYNCAPI_FILES=

WORKDIR /services/documentation/
COPY package*.json .

RUN npm install -g nodemon
RUN npm install


ENTRYPOINT [ "nodemon", "--ext", "js,yaml", "--watch", "./srcs", "--watch", "/documentation", "srcs/index.js" ]

EXPOSE 3000
