FROM node:23.7-alpine3.20

RUN apk --no-cache add curl

WORKDIR /services/settings/
COPY package*.json .

RUN npm install -g nodemon
RUN npm install

ENTRYPOINT [ "nodemon", "--watch", "/modules", "--watch", "./srcs", "srcs/index.js" ]

EXPOSE 3000

HEALTHCHECK \
  --interval=30s \
  --timeout=5s \
  --retries=3 \
  --start-period=1s \
  --start-interval=5s \
  CMD curl http://localhost:3000/ || exit 1
