FROM node:23.7-alpine3.20

WORKDIR /services/${SERVICE}/
COPY package*.json .

RUN npm install -g nodemon
RUN npm install

ENTRYPOINT [ "nodemon", "--watch", "/modules", "--watch", "./srcs" , "srcs/index.js" ]

EXPOSE 3000
