FROM node:23.7-alpine3.20

RUN apk --no-cache add curl

HEALTHCHECK --interval=10s --timeout=5s --start-period=1s --start-interval=2s  --retries=3 \
  CMD curl http://localhost:3000/ || exit 1

WORKDIR /services/swagger/
COPY package*.json .

RUN npm install -g nodemon
RUN npm install

ENTRYPOINT [ "nodemon", "--watch", "/modules", "--watch", "./srcs", "--watch", "/documentation/", "-e", "yaml" , "srcs/index.js" ]

EXPOSE 3000
