FROM node:23.7-alpine3.20

RUN apk --no-cache add curl

WORKDIR /services/frontend/
COPY . .

RUN npm install

ENTRYPOINT [ "npm", "start" ]

EXPOSE 8080

HEALTHCHECK \
  --interval=30s \
  --timeout=5s \
  --retries=3 \
  --start-period=1s \
  --start-interval=5s  \
  CMD curl http://localhost:8080/ || exit 1
