FROM node:23.7-alpine3.20

RUN apk --no-cache add curl

HEALTHCHECK --interval=30s --timeout=5s --start-period=1s --start-interval=5s --retries=3  \
  CMD curl http://localhost:3000/ || exit 1

WORKDIR /services/pong/
COPY package*.json .

RUN npm install -g nodemon
RUN npm install

ENTRYPOINT [ "nodemon", "--signal", "SIGTERM","--watch", "/modules", "--watch", "./srcs" , "srcs/index.js" ]

EXPOSE 3000

