name: Build Docker images for production

on:
  push:
    branches:
      - production
      - main
  workflow_dispatch:

jobs:
  yatt-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image
        run: docker compose build
        working-directory: ./modules/

      - name: Tag image
        run: docker tag yatt-modules:latest ibertran/transcendence.yatt-modules:${{ github.ref_name }}

      - name: Push image
        run: docker push ibertran/transcendence.yatt-modules:${{ github.ref_name }}

  ibertran-dot-dev:
    needs: yatt-modules
    runs-on: ubuntu-22.04
    env:
      BASE_IMAGE: ibertran/transcendence.yatt-modules:${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build images
        run: docker compose -f docker-compose.ibertran.yaml build

      # - name: Generate .env
      #   run: |
      #     export GOOGLE_CLIENT_ID="example"
      #     export API42_CLIENT_ID="example"
      #     export API42_SECRET="example"
      #     ./env-generator.sh

      # - name: Up
      #   run: docker compose -f docker-compose.ibertran.yaml up -d --wait || docker compose -f docker-compose.ibertran.yaml logs

      # - name: Down
      #   if: always()
      #   run: docker compose -f docker-compose.ibertran.yaml down

      - name: Push images
        if: github.ref_name == 'production'
        run: docker compose -f docker-compose.ibertran.yaml push
