name: Build Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  yatt-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build
        run: docker compose build
        working-directory: ./modules/

      - name: Tag image
        run: docker tag yatt-modules:latest ibertran/transcendence.yatt-modules:latest

      # - name: Push
      #   run: docker push ibertran/transcendence.yatt-modules:latest

      - name: Save Docker image as tar file
        run: docker save ibertran/transcendence.yatt-modules:latest -o yatt-modules.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yatt-modules-image
          path: yatt-modules.tar

  ibertran-dot-dev:
    needs: yatt-modules
    runs-on: ubuntu-22.04
    env:
      BASE_IMAGE: ibertran/transcendence.yatt-modules:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build images with docker-compose
        run: |
          docker compose -f docker-compose.ibertran.yaml build
