name: Build ibertran.dev Docker images

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    # env:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Build yatt-modules image
        run: docker compose build
        working-directory: ./modules

      - name: Build yatt-modules image
        run: docker compose -f docker-compose.ibertran.yaml build

      - name: Push to Docker hub
        run: docker compose -f docker-compose.ibertran.yaml push

      - name: Tear down Docker Compose
        run: docker compose down
        if: always()
