name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CDN_JWT_SECRET: ${{ secrets.CDN_JWT_SECRET }}
      PASSWORD_PEPPER: ${{ secrets.PASSWORD_PEPPER }}
      TOKEN_MANAGER_SECRET: ${{ secrets.TOKEN_MANAGER_SECRET }}
      FRONTEND_URL: https://localhost:8080
      BACKEND_URL: https://localhost:7979
      CDN_URL: https://cdn-nginx:8181
      API42_CLIENT_ID: 'example'
      API42_SECRET: 'example'
      API42_REDIRECT_URI: 'https://fake-callback.com'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.3.0'


      - name: Create SSL certificate
        run: make

      - name: Install dependencies
        run: npm install
        working-directory: ./tests

      - name: Build and run Docker Compose
        run: docker compose up -d

      - name : Check containers status
        run: 'sleep 10 && docker compose ps --format "{{.Name}}: {{.Status}}"'

      - name: Run Jest tests
        run: npm run action
        working-directory: ./tests

      - name: Print containers logs on test failure
        if: always()
        run: docker compose logs

      - name: Tear down Docker Compose
        run: docker compose down
        if: always()
