name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PASSWORD_PEPPER: ${{ secrets.PASSWORD_PEPPER }}
      TOKEN_MANAGER_SECRET: ${{ secrets.TOKEN_MANAGER_SECRET }}
      BACKEND_URL: http://127.0.0.1:7979
      FRONTEND_URL: http://127.0.0.1:8080
      API42_CLIENT_ID: 'example'
      API42_SECRET: 'example'
      API42_REDIRECT_URI: 'http://127.0.0.1:7979/auth/42/callback'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.3.0'

      - name: Create SSL certificate
        run: make

      - name: Install dependencies
        run: npm install
        working-directory: ./tests

      - name: Build and run Docker Compose
        run: docker compose up -d

      - name: Run Jest tests
        run: npm run action
        working-directory: ./tests

      - name: Tear down Docker Compose
        run: docker compose down
        if: always()
